### ISSUE TITLE
English docs

### ISSUE THREAD

**Issue by felixfong227** [twi-project/twi-server#8]
It will be nice if this repo got an English set of docs

**Comment by octet-stream** [comment]
Hello! Thanks for your feedback. :)

The project is still in development and now I working on port from CoffeeScript. So, I'll add an English version of docs closer to the first release.

Regards,
Nick K.

**Comment by felixfong227** [comment]
Cuz I want to help, but I have no idea what this project does 😕

**Comment by octet-stream** [comment]
This is just an engine for fanfiction library, like [ponyFinction](https://github.com/everypony/ponyFiction) or [fimfiction.net](fimfiction.net)

The project in early stage and don't have stable API for developers. So, I don't approve pull requests for now. Sorry for that :)

**Comment by octet-stream** [comment]
Checklist for this issue:
- [ ] Translate introduction.md and installation.md to English;
- [ ] Remove i18n support from an app.

**Comment by octet-stream** [comment]
Added drafts of English docs in https://github.com/octet-stream/twi/commit/ca3a66a6a95541bbab9f66071bfde522aa53a06d

But you're still can't run an application on your local machine while I'm working on this #9 issue.
Bu the way, if you're using Windows, you also can't run this project, because I don't support this operation system. Only **macOS** (actually, I mostly focused on it right now) or **Linux**.

**Comment by octet-stream** [comment]
Close #8 because the documentation will be only on English.
